(() => {
const c=window.MODO_PORTAL_CONFIG||{},ready=Boolean(c.supabaseUrl&&c.supabaseAnonKey&&window.supabase),db=ready?window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey):null,msg=document.querySelector('#editorMessage'),grantMsg=document.querySelector('#grantMessage');
const say=(el,text,type='')=>{el.textContent=text;el.className=`form-message ${type}`.trim()};
function getRoute(){let content;try{content=JSON.parse(document.querySelector('#routeContent').value||'{"sections":[]}')}catch(e){throw Error(`O conteúdo não está em JSON válido: ${e.message}`)}return{slug:document.querySelector('#routeSlug').value.trim(),status:document.querySelector('#routeStatus').value,title:document.querySelector('#routeTitle').value.trim(),subtitle:document.querySelector('#routeSubtitle').value.trim(),destination:document.querySelector('#routeDestination').value.trim(),duration:document.querySelector('#routeDuration').value.trim(),season:document.querySelector('#routeSeason').value.trim(),version:document.querySelector('#routeVersion').value.trim(),intro:document.querySelector('#routeIntro').value.trim(),cover_image:document.querySelector('#routeCover').value.trim(),overview:{style:'equilibrado',profile:'primeira viagem / casal / amigas / família / solo'},content};}
function fill(r){document.querySelector('#routeSlug').value=r.slug||'';document.querySelector('#routeStatus').value=r.status||'draft';document.querySelector('#routeTitle').value=r.title||'';document.querySelector('#routeSubtitle').value=r.subtitle||'';document.querySelector('#routeDestination').value=r.destination||'';document.querySelector('#routeDuration').value=r.duration||'';document.querySelector('#routeSeason').value=r.season||'';document.querySelector('#routeVersion').value=r.version||'';document.querySelector('#routeIntro').value=r.intro||'';document.querySelector('#routeCover').value=r.cover_image||'';document.querySelector('#routeContent').value=JSON.stringify(r.content||{sections:[]},null,2)}
async function verify(){if(!db){say(msg,'Modo demonstração: editor e prévia funcionam. Para salvar e liberar clientes, conecte o Supabase.','warning');return}const {data:s}=await db.auth.getSession();if(!s.session)return location.replace('index.html');const {data}=await db.from('profiles').select('is_admin').eq('id',s.session.user.id).single();if(!data?.is_admin)location.replace('dashboard.html')}
document.querySelector('#loadExampleButton').onclick=()=>fill(window.MODO_PREVIEW_ITINERARY);
document.querySelector('#previewButton').onclick=()=>{try{sessionStorage.setItem('modoPortalDraft',JSON.stringify(getRoute()));window.open('roteiro.html?draft=1','_blank','noopener');say(msg,'Prévia aberta em uma nova aba.','success')}catch(e){say(msg,e.message,'error')}};
document.querySelector('#itineraryForm').addEventListener('submit',async e=>{e.preventDefault();try{if(!db)throw Error('Conecte o Supabase para salvar. A prévia já funciona sem ele.');const {error}=await db.from('itineraries').upsert(getRoute(),{onConflict:'slug'});if(error)throw error;say(msg,'Roteiro salvo ✨ O design foi aplicado automaticamente.','success')}catch(e){say(msg,e.message,'error')}});
document.querySelector('#grantForm').addEventListener('submit',async e=>{e.preventDefault();if(!db)return say(grantMsg,'Conecte o Supabase para liberar acessos reais.','warning');const expiry=document.querySelector('#grantExpiry').value||null;const {data,error}=await db.rpc('grant_itinerary_access_by_email',{customer_email:document.querySelector('#grantEmail').value.trim(),itinerary_slug:document.querySelector('#grantSlug').value.trim(),expires_at_value:expiry?new Date(`${expiry}T23:59:59`).toISOString():null});say(grantMsg,error?error.message:(data||'Acesso liberado.'),error?'error':'success')});
document.querySelector('#adminSignOutButton').onclick=async()=>{if(db)await db.auth.signOut();location.replace('index.html')};fill(window.MODO_PREVIEW_ITINERARY);verify();
})();