(() => {
  const c=window.MODO_PORTAL_CONFIG||{}, q=new URLSearchParams(location.search), demo=q.get('demo')==='1'||sessionStorage.getItem('modoPortalDemo')==='1';
  const ready=Boolean(c.supabaseUrl&&c.supabaseAnonKey&&window.supabase), db=ready?window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey):null;
  const grid=document.querySelector('#routesGrid'), load=document.querySelector('#loadingState'), empty=document.querySelector('#emptyState'), count=document.querySelector('#routeCount');
  const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  function card(r,d=false){const href=`roteiro.html?slug=${encodeURIComponent(r.slug)}${d?'&demo=1':''}`;return `<article class="route-card"><div class="route-cover" style="background-image:url('${esc(r.cover_image||'../images/destinos/santiago.jpg')}')"><span class="route-status">${d?'Demonstração':'Liberado'}</span></div><div class="route-card-body"><span class="eyebrow">${esc(r.destination||'Roteiro Modo')}</span><h3>${esc(r.title)}</h3><p>${esc(r.subtitle||r.intro||'')}</p><div class="route-meta"><span>🗓️ ${esc(r.duration||'Consulte o roteiro')}</span>${r.season?`<span>🌤️ ${esc(r.season)}</span>`:''}</div><a class="btn btn-primary" href="${href}">Abrir roteiro →</a></div></article>`;}
  function render(routes,d=false){load.classList.add('is-hidden');count.textContent=`${routes.length} ${routes.length===1?'roteiro':'roteiros'}`;if(!routes.length){empty.classList.remove('is-hidden');return;}grid.innerHTML=routes.map(r=>card(r,d)).join('');}
  async function real(){if(!db)return location.replace('index.html');const {data:s}=await db.auth.getSession();if(!s.session)return location.replace('index.html');const u=s.session.user;document.querySelector('#userGreeting').textContent=`Oi, ${u.user_metadata?.full_name||u.email?.split('@')[0]||'viajante'}`;const {data:p}=await db.from('profiles').select('is_admin').eq('id',u.id).maybeSingle();if(p?.is_admin)document.querySelector('#adminLink').classList.remove('is-hidden');const {data,error}=await db.from('itinerary_access').select('access_expires_at,itineraries(*)').or(`access_expires_at.is.null,access_expires_at.gt.${new Date().toISOString()}`).order('created_at',{ascending:false});if(error){load.textContent='Não consegui carregar seus roteiros agora.';return;}render((data||[]).map(x=>x.itineraries).filter(Boolean));}
  document.querySelector('#signOutButton').addEventListener('click',async()=>{sessionStorage.removeItem('modoPortalDemo');if(db)await db.auth.signOut();location.replace('index.html');});
  if(demo){document.querySelector('#userGreeting').textContent='Modo demonstração';render([{slug:'andes-na-janela',title:'Andes na Janela',subtitle:'5 dias em Santiago (inverno)',destination:'Santiago, Chile',duration:'5 dias',season:'Inverno',cover_image:'../images/destinos/santiago.jpg'}],true);}else real();
})();