(() => {
const c=window.MODO_PORTAL_CONFIG||{},p=new URLSearchParams(location.search),slug=p.get('slug')||'andes-na-janela',demo=p.get('demo')==='1'||sessionStorage.getItem('modoPortalDemo')==='1',draft=p.get('draft')==='1',ready=Boolean(c.supabaseUrl&&c.supabaseAnonKey&&window.supabase),db=ready?window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey):null;
const root=document.querySelector('#itineraryRoot'),nav=document.querySelector('#summaryNav'),side=document.querySelector('#itinerarySidebar'),backdrop=document.querySelector('#sidebarBackdrop');
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const url=(v='')=>{try{const u=new URL(v,location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
const btn=a=>{const u=url(a?.url);return u?`<a class="content-button" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(a.label||'Abrir')}</a>`:''};
function cover(r){const o=r.overview||{};return `<section class="itinerary-cover" id="inicio"><div class="cover-image" style="background-image:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.45)),url('${esc(r.cover_image||'../images/destinos/santiago.jpg')}')"></div><div class="cover-content"><span class="eyebrow eyebrow-orange">Roteiro Pronto</span><div class="cover-emojis">${esc(r.emojis||'🗻 🇨🇱 ❄️')}</div><h1>${esc(r.title)}</h1><h2>${esc(r.subtitle||'')}</h2><p>${esc(r.intro||'')}</p><div class="overview-card"><h3>🗺️ Visão geral da viagem</h3><dl><div><dt>Destino</dt><dd>${esc(r.destination||'')}</dd></div><div><dt>Duração</dt><dd>${esc(r.duration||'')}</dd></div><div><dt>Estilo</dt><dd>${esc(o.style||'')}</dd></div><div><dt>Perfil</dt><dd>${esc(o.profile||'')}</dd></div></dl><strong>Tudo foi pensado pra ficar fácil de abrir no celular no meio da viagem.</strong></div></div></section>`}
function cards(s){return `<div class="content-grid">${(s.items||[]).map(i=>`<article class="content-card"><h3>${esc(i.icon||'')} ${esc(i.title)}</h3>${i.text?`<p>${esc(i.text)}</p>`:''}${i.note?`<p class="card-note">${esc(i.note)}</p>`:''}${i.actions?.length?`<div class="content-actions">${i.actions.map(btn).join('')}</div>`:''}</article>`).join('')}</div>`}
function budget(s){return `<div class="budget-grid">${(s.items||[]).map(i=>`<article class="budget-card"><h3>${esc(i.icon||'')} ${esc(i.title)}</h3><ul>${(i.ranges||[]).map(r=>`<li><span>${esc(r.label)}</span><strong>${esc(r.value)}</strong></li>`).join('')}</ul>${i.note?`<p>${esc(i.note)}</p>`:''}</article>`).join('')}</div>${s.summary?`<div class="highlight-box">${esc(s.summary)}</div>`:''}`}
function reservations(s){return `<div class="reservation-list">${(s.items||[]).map((i,n)=>`<article class="reservation-card"><span class="reservation-number">${String(n+1).padStart(2,'0')}</span><div><span class="eyebrow">${esc(i.label||'Antes de reservar')}</span><h3>${esc(i.icon||'')} ${esc(i.title)}</h3><p>${esc(i.text||'')}</p>${i.actions?.length?`<div class="content-actions">${i.actions.map(btn).join('')}</div>`:''}</div></article>`).join('')}</div>`}
function days(s){return `<div class="days-list">${(s.items||[]).map(d=>`<article class="day-card" id="${esc(d.id||'')}"><div class="day-head"><span class="day-number">${esc(d.label||'')}</span><div><h3>${esc(d.title)}</h3><p>${esc(d.summary||'')}</p></div></div>${d.tags?.length?`<div class="tag-row">${d.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:''}<div class="timeline">${(d.stops||[]).map(st=>`<div class="timeline-item"><div class="timeline-time">${esc(st.time||'Ao longo do dia')}</div><div class="timeline-copy"><h4>${esc(st.icon||'')} ${esc(st.title)}</h4><p>${esc(st.text||'')}</p>${st.actions?.length?`<div class="content-actions">${st.actions.map(btn).join('')}</div>`:''}</div></div>`).join('')}</div>${d.tip?`<div class="modo-tip"><strong>💙 Dica Modo</strong><p>${esc(d.tip)}</p></div>`:''}</article>`).join('')}</div>`}
function options(s){return `<div class="options-grid">${(s.items||[]).map(i=>`<article class="option-card"><div class="option-top"><span class="option-icon">${esc(i.icon||'📍')}</span>${i.price?`<span class="price-pill">${esc(i.price)}</span>`:''}</div><h3>${esc(i.title)}</h3>${i.subtitle?`<strong>${esc(i.subtitle)}</strong>`:''}<p>${esc(i.text||'')}</p>${i.tags?.length?`<div class="tag-row">${i.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:''}${i.actions?.length?`<div class="content-actions">${i.actions.map(btn).join('')}</div>`:''}</article>`).join('')}</div>`}
function links(s){return `<div class="links-grid">${(s.items||[]).map(i=>{const u=url(i.url),tag=u?'a':'div',attrs=u?`href="${esc(u)}" target="_blank" rel="noopener noreferrer"`:'';return `<${tag} class="link-card ${u?'':'is-disabled'}" ${attrs}><span>${esc(i.icon||'🔗')}</span><div><strong>${esc(i.title)}</strong><small>${esc(i.text||'')}</small></div><b>→</b></${tag}>`}).join('')}</div>`}
function checklist(s,routeSlug){const key=`modo-checklist-${routeSlug}`;let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{};setTimeout(()=>document.querySelectorAll('[data-check-id]').forEach(x=>x.addEventListener('change',()=>{saved[x.dataset.checkId]=x.checked;localStorage.setItem(key,JSON.stringify(saved))})),0);return `<div class="checklist-grid">${(s.groups||[]).map((g,gi)=>`<article class="checklist-group"><h3>${esc(g.icon||'✅')} ${esc(g.title)}</h3><div>${(g.items||[]).map((it,ii)=>{const id=`check-${gi}-${ii}`;return `<label class="check-item" for="${id}"><input id="${id}" type="checkbox" data-check-id="${id}" ${saved[id]?'checked':''}/><span>${esc(it)}</span></label>`}).join('')}</div></article>`).join('')}</div>`}
function closing(s){return `<div class="closing-card"><div class="closing-icon">${esc(s.icon||'✈️')}</div><h3>${esc(s.title||'')}</h3><p>${esc(s.text||'')}</p>${s.actions?.length?`<div class="content-actions centered">${s.actions.map(btn).join('')}</div>`:''}</div>`}
function section(s,routeSlug){const f={cards,budget,reservations,days,options,links,checklist:x=>checklist(x,routeSlug),closing}[s.type];if(!f)return'';return `<section class="itinerary-section" id="${esc(s.id)}"><div class="section-intro">${s.tag?`<span class="eyebrow ${s.tagColor==='orange'?'eyebrow-orange':''}">${esc(s.tag)}</span>`:''}<h2>${esc(s.title||'')}</h2>${s.subtitle?`<p>${esc(s.subtitle)}</p>`:''}</div>${f(s)}</section>`}
function render(r){document.title=`${r.title} | Modo Turistagem`;root.innerHTML=`${cover(r)}${(r.content?.sections||[]).map(s=>section(s,r.slug)).join('')}<footer class="itinerary-footer"><img src="../images/LOGOTIPO%20branco.png" alt="Modo Turistagem" /><p>Uso pessoal • Reprodução não autorizada • Versão ${esc(r.version||'')}</p></footer>`;nav.innerHTML=[{id:'inicio',title:'Capa'},...(r.content?.sections||[]).map(s=>({id:s.id,title:s.navTitle||s.title}))].map(x=>`<a href="#${esc(x.id)}">${esc(x.title)}</a>`).join('');nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));}
async function load(){if(draft){const raw=sessionStorage.getItem('modoPortalDraft');if(!raw)throw Error('Rascunho não encontrado.');return render(JSON.parse(raw))}if(demo){if(!window.MODO_PREVIEW_ITINERARY)throw Error('Demonstração indisponível.');return render(window.MODO_PREVIEW_ITINERARY)}if(!db)return location.replace('index.html');const {data:s}=await db.auth.getSession();if(!s.session)return location.replace('index.html');const {data,error}=await db.from('itineraries').select('*').eq('slug',slug).eq('status','published').single();if(error||!data)throw Error('Esse roteiro não está liberado para esta conta.');render(data)}
function open(){side.classList.add('is-open');backdrop.classList.add('is-open')}function close(){side.classList.remove('is-open');backdrop.classList.remove('is-open')}
document.querySelector('#summaryButton').onclick=open;document.querySelector('#floatingSummaryButton').onclick=open;document.querySelector('#closeSummaryButton').onclick=close;backdrop.onclick=close;document.querySelector('#printButton').onclick=()=>print();load().catch(e=>root.innerHTML=`<div class="state-card itinerary-error"><strong>Não consegui abrir o roteiro.</strong><p>${esc(e.message)}</p><a class="btn btn-primary" href="dashboard.html">Voltar</a></div>`);
})();